
fragment ContinentParts on Continent {
  code
  name
}

POST https://countries.trevorblades.com/graphql
Content-Type: application/json

query Continents {
    continents {
      ...ContinentParts
    }
}

{
    "code": "EU"
}