# @ref json
# @import ./ref.http
GET /json

{{
  const { equal } = require('assert');
  test('status code 200', () => {
    equal(response.statusCode, 200);
  });
  test('status code 200', () => {
    equal(response.statusCode, 200);
  });
}}


###
# @ref json
# @import ./ref.http

GET /json

{{
  const { equal } = require('assert');
  test('status code 200', () => {
    equal(response.statusCode, 200);
  });
  test('status code 200', () => {
    equal(response.statusCode, 200);
  });
}}

###
# @ref json
# @import ./ref.http

GET /json

{{
  const { equal } = require('assert');
  test('status code 200', () => {
    equal(response.statusCode, 200);
  });
  test('status code 200', () => {
    equal(response.statusCode, 200);
  });
}}



###
# @ref json
# @import ./ref.http

GET /json

{{
  const { equal } = require('assert');
  test('status code 200', () => {
    equal(response.statusCode, 200);
  });
  test('status code 200', () => {
    equal(response.statusCode, 200);
  });
}}
