proto < ./hello.proto
@host=grpc.postman-echo.com/HelloService

###

GRPC /sayHello
{
  "greeting": "2342"
}

GRPC /LotsOfReplies
{
  "greeting": "2342"
}

GRPC /lotsOfGreetings
{
  "greeting": "world."
}

{{@streaming

  async function writeStream(){
    await sleep(1000);
    $requestClient.send({
      greeting: 'How are you?',
    });
    await sleep(1000);
    $requestClient.send({
      greeting: 'I can stream.',
    });
  }
  exports.waitPromise = writeStream();
}}

GRPC /BidiHello
{
  "greeting": "world"
}

{{@streaming

  async function writeStream(){
    await sleep(1000);
    $requestClient.send({
      greeting: ', how are you?',
    });
    await sleep(1000);
    $requestClient.send({
      greeting: ', I can stream.',
    });
  }
  exports.waitPromise = writeStream();
}}