
GET https://postman-echo.com/get
{{
  const Ajv = require("ajv")

const schema = {
  type: "object",
  properties: {
    args: {type: "object"},
    url: {type: "string"}
  },
  required: ["url"],
  additionalProperties: false
}


test('has invalid json schema', () => {
  const ajv = new Ajv();
  const validate = ajv.compile(schema)
  const valid = validate(response.parsedBody)
  if (!valid) {
    console.error(validate.errors)
    throw new Ajv.ValidationError(validate.errors);
  }
});

}}