MQTT tcp://broker.hivemq.com
Topic: testtopic/1

{{@streaming
  async function writeStream(){
    await sleep(1000);
    mqttClient.publish('testtopic/1', 'Hello World');
    await sleep(1000);
  }
  exports.waitPromise = writeStream();
}}