MQTT tcp://broker.hivemq.com
publish: httpyac

{{@streaming
  async function writeStream(){
    await sleep(1000);
    $requestClient.send("mqttPublish");
    await sleep(1000);
  }
  exports.waitPromise = writeStream();
}}