POST https://postman-echo.com/post

{
  "foo": "bar"
}

> {%
    client.test("Request executed successfully", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}