proto < ./hello.proto
GRPC grpc.postman-echo.com/HelloService/BidiHello
{
  "greeting": "world"
}
===
{
  "greeting": "How are you?"
}
=== wait-for-server
=== wait-for-server
{
  "greeting": "I can stream."
}
