proto < ./hello.proto
GRPC grpc.postman-echo.com/HelloService/BidiHello
{
  "greeting": "world"
}

{{@streaming

  async function writeStream(){
    await sleep(1000);
    $requestClient.send({
      greeting: ', how are you?',
    });
    await sleep(1000);
    $requestClient.send({
      greeting: ', I can stream.',
    });
  }
  exports.waitPromise = writeStream();
}}