proto < ./hello.proto

{{@request
const grpc = require('@grpc/grpc-js');
request.channelCredentials = grpc.ChannelCredentials.createSsl();
}}
GRPC grpc.postman-echo.com/HelloService/sayHello
{
  "greeting": "world"
}