proto < ./hello.proto

{{@request
const grpc = require('@grpc/grpc-js');
request.headers.channelcredentials = grpc.ChannelCredentials.createSsl();
}}
GRPC grpcb.in:9001/hello.HelloService/sayHello
{
  "greeting": "world"
}