proto < ./hello.proto
keepCase: true
longs: String
enums: String
defaults: true
oneofs: true
includeDirs: [`${__dirname}/request`]

GRPC grpc.postman-echo.com/HelloService/sayHello
{
  "greeting": "world"
}