proto < ./hello.proto
GRPC grpcb.in:9000/hello.HelloService/lotsOfGreetings
{
  "greeting": "world."
}

{{@streaming

  async function writeStream(){
    await sleep(1000);
    grpcStream.write({
      greeting: 'How are you?',
    });
    await sleep(1000);
    grpcStream.write({
      greeting: 'I can stream.',
    });
  }
  exports.waitPromise = writeStream();
}}