{{+
  const token = "test"
  exports.defaultHeaders = {
    'Content-Type': 'text/html',
    'Authorization': `Bearer ${token}`
  };
}}
###
GET https://httpbin.org/anything HTTP/1.1
...defaultHeaders
GET https://httpbin.org/anything HTTP/1.1
...defaultHeaders