@assetsDir=./

proto < {{assetsDir}}hello.proto
keepCase: true
longs: String
enums: String
defaults: true
oneofs: true
includeDirs: ["../request"]

GRPC grpcb.in:9000/hello.HelloService/sayHello
{
  "greeting": "world"
}