proto < ./hello.proto
proto < ./grpcbin.proto

@host=grpcb.in:9000

###

GRPC /hello.HelloService/sayHello
{
  "greeting": "world"
}

GRPC /hello.HelloService/LotsOfReplies
{
  "greeting": "world"
}


GRPC /hello.HelloService/lotsOfGreetings
{
  "greeting": "world."
}

{{@streaming

  async function writeStream(){
    sleep(1000);
    grpcStream.write({
      greeting: 'How are you?',
    });
    sleep(1000);
    grpcStream.write({
      greeting: 'I can stream.',
    });
  }
  exports.waitPromise = writeStream();
}}

GRPC /hello.HelloService/BidiHello
{
  "greeting": "world"
}

{{@streaming

  async function writeStream(){
    sleep(1000);
    grpcStream.write({
      greeting: ', how are you?',
    });
    sleep(1000);
    grpcStream.write({
      greeting: ', I can stream.',
    });
  }
  exports.waitPromise = writeStream();
}}


GRPC /grpcbin.GRPCBin/SpecificError
{
  "code": 4,
  "reason": "Meaning of life"
}
GRPC /grpcbin.GRPCBin/RandomError
{
  "fString": "bar"
}
GRPC /grpcbin.GRPCBin/HeadersUnary


GRPC /grpcbin.GRPCBin/NoResponseUnary