POST https://countries.trevorblades.com/graphql
Content-Type: application/json

query Continents($code: String!) {
    continents(filter: {code: {eq: $code}}) {
      code
      name
    }
}

{
    "code": "EU"
}