WS wss://socketsbay.com/wss/v2/1/demo/

{
  "test": "httpyac"
}

{{@streaming
  async function writeStream(){
    await sleep(10000);
    $requestClient.send({
      "event": "ping",
      "reqid": 45
    });
    await sleep(1000);
  }
  exports.waitPromise = writeStream();
}}