GET /anything?q={{$guid}} HTTP/1.1

GET /anything?q={{$randomInt 100 200}} HTTP/1.1

GET /anything?q={{$randomInt -100 100}} HTTP/1.1

GET /anything?q={{$randomInt -100 -50}} HTTP/1.1

GET /anything?q={{$randomInt -50 -100}} HTTP/1.1

GET /anything?q={{$timestamp}} HTTP/1.1

GET /anything?q={{$timestamp 2 h}} HTTP/1.1

GET /anything?q={{$datetime rfc1123}} HTTP/1.1

GET /anything?q={{$datetime rfc1123 2 h}} HTTP/1.1

GET /anything?q={{$datetime iso8601}} HTTP/1.1

GET /anything?q={{$datetime iso8601 2 h}} HTTP/1.1

GET /anything?q={{$datetime "DD.MM.YYYY"}} HTTP/1.1

GET /anything?q={{$datetime "DD.MM.YYYY" 2 d}} HTTP/1.1

GET /anything?q={{$datetime 'DD.MM.YYYY'}} HTTP/1.1

GET /anything?q={{$datetime 'DD.MM.YYYY' 3 d}} HTTP/1.1

GET /anything?q={{$localDatetime rfc1123}} HTTP/1.1

GET /anything?q={{$localDatetime rfc1123 2 h}} HTTP/1.1

GET /anything?q={{$localDatetime iso8601}} HTTP/1.1

GET /anything?q={{$localDatetime iso8601 2 h}} HTTP/1.1

GET /anything?q={{$localDatetime "DD.MM.YYYY HH:mm"}} HTTP/1.1

GET /anything?q={{$datetime "DD.MM.YYYY HH:mm" 2 d}} HTTP/1.1

GET /anything?q={{$datetime 'DD.MM.YYYY HH:mm'}} HTTP/1.1

GET /anything?q={{$datetime 'DD.MM.YYYY HH:mm' 3 d}} HTTP/1.1