GET https://httpbin.org/anything

> {% client.global.set("header", "h1") %}

###

GET https://httpbin.org/anything
X-Header: {{header}}

> {% client.global.set("header", "h2") %}

###

GET https://httpbin.org/anything
X-Header: {{header}}

###