
{{
  const { authenticate } = require('./scriptRequire.cjs');
  const authDate = new Date();

  exports.authDate = authDate.toUTCString();
  exports.authentication = authenticate(authDate, request);
}}

GET https://httpbin.org/anything
Authentication: {{authentication}}
Date: {{authDate}}