{{
  //pre request script
  const crypto = require('crypto');
  const date = new Date();
  const signatureBase64 = crypto.createHmac('sha256', 'secret')
  .update(`${request.method}\u2028${request.url}\u2028${date.getTime()}`).digest("base64");
  exports.authDate = date.toUTCString();
  exports.authentication = `Basic ${signatureBase64}`;
}}
GET https://httpbin.org/anything
Date: {{authDate}}
Authentication: {{authentication}}

{{
  // post request script
  const assert = require('assert');
  test("authentication is valid", () => {
    assert.equal(response.parsedBody.headers.Authentication, authentication);
  });
}}